
DROP TABLE PBIDMAUVAISEGESTIONDESID;
DROP TABLE PBID;


CREATE MEMORY TABLE PBIDMAUVAISEGESTIONDESID(
    MATRICULE INTEGER NOT NULL ,
    CODE INTEGER NOT NULL ,
    DESCRIPTION VARCHAR(100) NOT NULL,
    PRIMARY KEY(MATRICULE, CODE));

INSERT INTO PBIDMAUVAISEGESTIONDESID VALUES(1,32,'pbid1');
INSERT INTO PBIDMAUVAISEGESTIONDESID VALUES(1,33,'pbid2');

INSERT INTO PBIDMAUVAISEGESTIONDESID VALUES(2,34,'pbid3');
INSERT INTO PBIDMAUVAISEGESTIONDESID VALUES(2,35,'pbid4');



CREATE MEMORY TABLE PBID(
    MATRICULE INTEGER NOT NULL ,
    CODE INTEGER NOT NULL ,
    DESCRIPTION VARCHAR(100) NOT NULL,
    PRIMARY KEY(MATRICULE,CODE));

INSERT INTO PBID VALUES(1,32,'pbid1');
INSERT INTO PBID VALUES(1,33,'pbid2');

INSERT INTO PBID VALUES(2,34,'pbid3');
INSERT INTO PBID VALUES(2,35,'pbid4');